# Generated by Django 3.0.4 on 2020-06-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='nama',
            new_name='nama_produk',
        ),
        migrations.AddField(
            model_name='produk',
            name='foto',
            field=models.ImageField(default='default', upload_to='upload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produk',
            name='nama_toko',
            field=models.CharField(default='ud77', max_length=255),
            preserve_default=False,
        ),
    ]
