# Generated by Django 3.0.4 on 2020-06-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200617_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='foto',
            field=models.ImageField(upload_to='E:\\Martassar\\Projek\\Martassar\\assets\\upload'),
        ),
    ]
