# Generated by Django 3.0.4 on 2020-06-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200617_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=255)),
                ('harga_produk', models.CharField(max_length=255)),
                ('jumlah', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('transaction', models.BooleanField()),
                ('transaction_time', models.DateTimeField()),
                ('success', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
    ]
